/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jeo_core_VSTFactory_AIS */

#ifndef _Included_jeo_core_VSTFactory_AIS
#define _Included_jeo_core_VSTFactory_AIS
#ifdef __cplusplus
extern "C" {
#endif
#undef jeo_core_VSTFactory_AIS_SKIP_BUFFER_SIZE
#define jeo_core_VSTFactory_AIS_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
