/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jeo_decoder_WmaPlayer */

#ifndef _Included_jeo_decoder_WmaPlayer
#define _Included_jeo_decoder_WmaPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef jeo_decoder_WmaPlayer_MAXVOLUME
#define jeo_decoder_WmaPlayer_MAXVOLUME 100L
/*
 * Class:     jeo_decoder_WmaPlayer
 * Method:    setVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jeo_decoder_WmaPlayer_setVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     jeo_decoder_WmaPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jeo_decoder_WmaPlayer_play
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jeo_decoder_WmaPlayer
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jeo_decoder_WmaPlayer_pause
  (JNIEnv *, jobject);

/*
 * Class:     jeo_decoder_WmaPlayer
 * Method:    resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jeo_decoder_WmaPlayer_resume
  (JNIEnv *, jobject);

/*
 * Class:     jeo_decoder_WmaPlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jeo_decoder_WmaPlayer_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
