/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jeo_core_VSTFactory */

#ifndef _Included_jeo_core_VSTFactory
#define _Included_jeo_core_VSTFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jeo_core_VSTFactory
 * Method:    process
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jeo_core_VSTFactory_process
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     jeo_core_VSTFactory
 * Method:    closeAllVst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jeo_core_VSTFactory_closeAllVst
  (JNIEnv *, jobject);

/*
 * Class:     jeo_core_VSTFactory
 * Method:    openAllVst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jeo_core_VSTFactory_openAllVst
  (JNIEnv *, jobject);

/*
 * Class:     jeo_core_VSTFactory
 * Method:    openEdit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jeo_core_VSTFactory_openEdit
  (JNIEnv *, jobject);

/*
 * Class:     jeo_core_VSTFactory
 * Method:    setBufferSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jeo_core_VSTFactory_setBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     jeo_core_VSTFactory
 * Method:    setSampleRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jeo_core_VSTFactory_setSampleRate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     jeo_core_VSTFactory
 * Method:    vstIsOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jeo_core_VSTFactory_vstIsOpen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
